from __future__ import annotations
import importlib.util,json
from pathlib import Path

B=Path(__file__).resolve().parents[1]
def load(p:Path,n:str):
    s=importlib.util.spec_from_file_location(n,p); assert s and s.loader
    m=importlib.util.module_from_spec(s); s.loader.exec_module(m); return m
V=load(B/"scripts"/"validate_pcr_current_all_confirmation_outcome.py","confirmation_outcome_fixture_validator")
D=load(B/"tests"/"test_pcr_discovery_decision_validation.py","confirmation_outcome_discovery_fixture")
def write(p:Path,x): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,indent=2,sort_keys=True)+"\n",encoding="utf-8")
def build(tmp:Path,outcome="CONFIRMED_CURRENT_TURN"):
    dpp,dap,dsp,dep,ddp=D.fixture(tmp/"discovery","SELECT_CURRENT_TURN_FOR_CONFIRMATION"); dv=V.DISCOVERY.validate(dpp,dap,dsp,dep,ddp); dp=json.loads(dpp.read_text())
    cp={"schema_version":"pcr.current_all.confirmation_plan.v1","status":"DRY_CONFIRMATION_PLAN_LIVE_LOCKED","production_commit":dp["production_commit"],"production_tree":dp["production_tree"],"task_freeze_sha256":dp["task_freeze_sha256"],"parent_execution_plan_authorization_code":dp["execution_plan_authorization_code"],"confirmation_plan_authorization_code":"a"*64}; cpp=tmp/"confirmation-plan.json"; write(cpp,cp)
    ca={"schema_version":"pcr.current_all.confirmation_adjudication.v1","status":"CONFIRMATION_MECHANICAL_COMPLETE_BLIND_REVIEW_REQUIRED","all_blocks_mechanically_valid":True,"valid_row_count":4,"valid_block_count":2,"cognition_selection":None,"confirmation_outcome":None,"merge_ready":False,"production_commit":cp["production_commit"],"production_tree":cp["production_tree"],"task_freeze_sha256":cp["task_freeze_sha256"],"confirmation_plan_authorization_code":cp["confirmation_plan_authorization_code"],"blocks":[{"block_id":bid,"valid":True,"whole_block_semantic_admitted":True,"invalid_rows":[],"pair_reasons":[]} for bid in V._BLOCKS]}; cap=tmp/"confirmation-adjudication.json"; write(cap,ca)
    seal={"schema_version":"pcr.current_all.confirmation_blind_review_seal.v1","status":"CONFIRMATION_BLIND_REVIEW_SEALED_UNBLIND_ALLOWED","row_count":4,"treatment_labels_exposed_during_review":False,"confirmation_outcome":None,"merge_ready":False}; seal["seal_sha256"]=V.csha(seal); csp=tmp/"confirmation-seal.json"; write(csp,seal)
    ctx=V._OUTCOMES[outcome]; passed=ctx is not None; pairs=[{"block_id":bid,"family":fam,"pair_mechanically_valid":True,"anonymous_semantic_preference":"no_meaningful_semantic_difference","semantic_evidence_refs":[],"task_outcome_current_turn":"pass","task_outcome_all_turns":"pass","semantic_preference_after_unblinding":"tie","provider_protocol_notes":"valid","repetition_efficiency_notes":"matched","economics_notes":"separate"} for bid,fam in V._BLOCKS.items()]
    ev={"schema_version":"pcr.current_all.confirmation_outcome_evidence.v1","production_commit":cp["production_commit"],"production_tree":cp["production_tree"],"task_freeze_sha256":cp["task_freeze_sha256"],"discovery_decision_validation_sha256":V.csha(dv),"discovery_selected_reasoning_context":"current_turn","confirmation_plan_authorization_code":cp["confirmation_plan_authorization_code"],"confirmation_adjudication_sha256":V.fsha(cap),"confirmation_blind_review_seal_sha256":seal["seal_sha256"],"row_count":4,"valid_block_count":2,"all_blocks_mechanically_valid":True,"weighted_scalar_selection_used":False,"grader_only_selection_used":False,"pairs":pairs,"proposed_outcome":outcome,"proposed_reasoning_context":ctx,"confirmation_passed":passed,"cognition_selection_resolved":passed,"merge_ready":False}; cep=tmp/"confirmation-evidence.json"; write(cep,ev)
    rec={"schema_version":"pcr.current_all.confirmation_outcome.v1","status":"SEALED_CONFIRMATION_OUTCOME","production_commit":cp["production_commit"],"production_tree":cp["production_tree"],"task_freeze_sha256":cp["task_freeze_sha256"],"confirmation_plan_authorization_code":cp["confirmation_plan_authorization_code"],"discovery_decision_validation_sha256":V.csha(dv),"confirmation_adjudication_sha256":V.fsha(cap),"confirmation_blind_review_seal_sha256":seal["seal_sha256"],"confirmation_outcome_evidence_sha256":V.fsha(cep),"outcome":outcome,"reasoning_context":ctx,"outcome_frozen":True,"confirmation_passed":passed,"cognition_selection_resolved":passed,"merge_ready":False}; cop=tmp/"confirmation-outcome.json"; write(cop,rec)
    return dpp,dap,dsp,dep,ddp,cpp,cap,csp,cep,cop
