# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv-store.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'kv-store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv-store.proto\x12\x07kvstore\"\x1c\n\rGetValRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1d\n\x0eGetValResponse\x12\x0b\n\x03val\x18\x01 \x01(\x05\")\n\rSetValRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x05\"\x1d\n\x0eSetValResponse\x12\x0b\n\x03val\x18\x01 \x01(\x05\x32\x7f\n\x07KVStore\x12\x39\n\x06GetVal\x12\x16.kvstore.GetValRequest\x1a\x17.kvstore.GetValResponse\x12\x39\n\x06SetVal\x12\x16.kvstore.SetValRequest\x1a\x17.kvstore.SetValResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETVALREQUEST']._serialized_start=27
  _globals['_GETVALREQUEST']._serialized_end=55
  _globals['_GETVALRESPONSE']._serialized_start=57
  _globals['_GETVALRESPONSE']._serialized_end=86
  _globals['_SETVALREQUEST']._serialized_start=88
  _globals['_SETVALREQUEST']._serialized_end=129
  _globals['_SETVALRESPONSE']._serialized_start=131
  _globals['_SETVALRESPONSE']._serialized_end=160
  _globals['_KVSTORE']._serialized_start=162
  _globals['_KVSTORE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
