"""Completion-contract and ledger-progress helpers for the Aether-2 control loop.

Responsibilities:
- Build the per-turn completion contract injected into the model context.
- Track evidence progress across turns (requirement advancement, provenance).
- Build suppressed-blocker and evidence-gate DiscrepancyReport objects.
- Classify semantic action families for failure-family tracking.
"""

from __future__ import annotations

import shlex
from typing import Any, Mapping

from harness.aether2.runtime.prompts import (
    COMPLETION_REMINDER_INTRO,
    STRATEGY_RESET_REMINDER,
    TASK_DONE_REMINDER,
)
from harness.aether2.runtime.verify import DiscrepancyReport, RequirementResult
from harness.aether2.traces.envelope import ObservationEnvelope

__all__ = [
    "_INDEPENDENT_PROVENANCE_LABELS",
    "_SELF_AUTHORED_PROVENANCE_LABELS",
    "_WEAK_EVIDENCE_STRENGTHS",
    "_active_blockers",
    "_build_completion_contract",
    "_build_completion_evidence_gate_report",
    "_build_suppressed_blocker_report",
    "_failure_class",
    "_ledger_progress",
    "_new_independent_provenance_added",
    "_primary_requirement",
    "_semantic_action_family",
    "_strength_rank",
]

_REQUIREMENT_PREVIEW_LIMIT = 4
_WEAK_EVIDENCE_STRENGTHS = {"none", "weak"}

# W1.2: provenance labels that indicate evidence was generated by the model's
# own artifact/check rather than an independent or externally observable
# source. Used only for a passive, model-visible reflection note -- never to
# veto or rewrite an action.
_SELF_AUTHORED_PROVENANCE_LABELS = {
    "model_authored_artifact",
    "model_authored_check",
    "same_method_check",
}

# Provenance labels that indicate the evidence was not merely self-authored
# (model-written artifact, replayed/same-method check, etc.). A newly added
# label from this set represents genuine independent evidence, distinct from
# a bare increase in evidence_refs count (e.g. an output write or status note).
_INDEPENDENT_PROVENANCE_LABELS = {
    "task_supplied",
    "external_tool_observation",
    "fresh_process",
    "fresh_client",
    "task_environment",
    "independent",
}


def _strength_rank(value: str) -> int:
    """Return a numeric rank for an evidence-strength string."""

    return {"none": 0, "weak": 1, "moderate": 2, "strong": 3}.get(value, 0)


def _new_independent_provenance_added(before_item: Mapping[str, Any], after_item: Mapping[str, Any]) -> bool:
    """Return True if a new independent-provenance label appeared in after_item."""

    before_labels = {str(label) for label in (before_item.get("evidence_provenance", []) or [])}
    after_labels = {str(label) for label in (after_item.get("evidence_provenance", []) or [])}
    newly_added = after_labels - before_labels
    return bool(newly_added & _INDEPENDENT_PROVENANCE_LABELS)


def _ledger_progress(before: Mapping[str, Any], after: Mapping[str, Any]) -> tuple[bool, bool]:
    """Return (requirement_advanced, stronger_evidence_added) comparing two ledgers."""

    from harness.aether2.control.requirements import _ledger_requirements, _ledger_requirement_text  # local import

    before_map = {
        _ledger_requirement_text(item): item
        for item in _ledger_requirements(before)
        if _ledger_requirement_text(item)
    }
    after_map = {
        _ledger_requirement_text(item): item
        for item in _ledger_requirements(after)
        if _ledger_requirement_text(item)
    }
    requirement_advanced = False
    stronger_evidence_added = False
    for requirement, after_item in after_map.items():
        before_item = before_map.get(requirement, {})
        if str(before_item.get("status", "unproven")) != str(after_item.get("status", "unproven")):
            requirement_advanced = True
        if _strength_rank(str(after_item.get("evidence_strength", "none"))) > _strength_rank(
            str(before_item.get("evidence_strength", "none"))
        ):
            stronger_evidence_added = True
        if _new_independent_provenance_added(before_item, after_item):
            stronger_evidence_added = True
    return requirement_advanced, stronger_evidence_added


def _build_completion_contract(task_instruction: str, ledger: Mapping[str, Any]) -> dict[str, Any]:
    """Build the per-turn completion contract injected into the model context."""

    from harness.aether2.control.requirements import (  # local import
        _ledger_requirement_text,
        _unresolved_requirements,
    )

    unresolved = _unresolved_requirements(ledger)
    weak_evidence: list[str] = []
    next_required: list[str] = []
    blockers: list[str] = []
    for item in unresolved:
        evidence_strength = str(item.get("evidence_strength", "none"))
        requirement = _ledger_requirement_text(item)
        if evidence_strength in _WEAK_EVIDENCE_STRENGTHS and list(item.get("evidence_refs", []) or []):
            weak_evidence.append(f"{requirement}: evidence is only {evidence_strength}")
        for blocker in list(item.get("verifier_blockers", []) or []):
            blockers.append(f"{requirement}: {blocker}")
        for evidence in list(item.get("next_required_evidence", []) or []):
            next_required.append(f"{requirement}: {evidence}")
    contract_text = " ".join(task_instruction.split())
    if len(contract_text) > 280:
        contract_text = contract_text[:277].rstrip() + "..."

    # W1.2: a concise, per-turn evidence question derived from visible state.
    # Passive reflection only -- it states the current unresolved requirement,
    # the strongest missing evidence for it, and (when applicable) that the
    # existing evidence for that requirement was only weak/self-authored.
    current_unresolved_requirement: str | None = None
    strongest_missing_evidence: str | None = None
    current_evidence_is_self_authored_or_weak: bool = False
    if unresolved:
        top = unresolved[0]
        current_unresolved_requirement = _ledger_requirement_text(top)
        top_next_required = list(top.get("next_required_evidence", []) or [])
        if top_next_required:
            strongest_missing_evidence = str(top_next_required[0])
        evidence_strength = str(top.get("evidence_strength", "none"))
        provenance_labels = {str(label) for label in (top.get("evidence_provenance", []) or [])}
        has_evidence = bool(list(top.get("evidence_refs", []) or []))
        if has_evidence and (
            evidence_strength in _WEAK_EVIDENCE_STRENGTHS
            or (provenance_labels and provenance_labels.issubset(_SELF_AUTHORED_PROVENANCE_LABELS))
        ):
            current_evidence_is_self_authored_or_weak = True

    return {
        "intro": COMPLETION_REMINDER_INTRO,
        "stated_task_contract": contract_text,
        "unresolved_requirements": [_ledger_requirement_text(item) for item in unresolved[:_REQUIREMENT_PREVIEW_LIMIT]],
        "verifier_blockers": blockers[:_REQUIREMENT_PREVIEW_LIMIT],
        "weak_evidence": weak_evidence[:_REQUIREMENT_PREVIEW_LIMIT],
        "next_required_evidence": next_required[:_REQUIREMENT_PREVIEW_LIMIT],
        "current_unresolved_requirement": current_unresolved_requirement,
        "strongest_missing_evidence": strongest_missing_evidence,
        "current_evidence_is_self_authored_or_weak": current_evidence_is_self_authored_or_weak,
        "strategy_reset_rule": STRATEGY_RESET_REMINDER,
        "task_done_rule": TASK_DONE_REMINDER,
    }


def _semantic_action_family(tool_name: str, arguments: Mapping[str, Any]) -> tuple[str, str | None, str | None]:
    """Return (family, target, target_kind) for the given tool call."""

    if tool_name != "run_command":
        for key, target_kind in (("path", "path"), ("job_id", "job"), ("session_id", "session"), ("cwd", "path")):
            raw = arguments.get(key)
            if isinstance(raw, str) and raw.strip():
                return tool_name, raw, target_kind
        return tool_name, None, None

    command = str(arguments.get("cmd", ""))
    try:
        tokens = shlex.split(command, posix=True)
    except ValueError:
        return "run_command", command.strip() or None, "command"
    if not tokens:
        return "run_command", None, None
    family_tokens = [tokens[0]]
    if len(tokens) > 1 and tokens[0] in {"python", "python3", "pytest", "bash", "sh", "node", "Rscript", "make", "cmake", "cargo", "go", "npm", "pip", "pip3", "uv"}:
        family_tokens.append(tokens[1])
    target = None
    target_kind = None
    for token in tokens[1:]:
        if token.startswith("-") or "://" in token:
            continue
        if "/" in token or token.endswith((".py", ".sh", ".txt", ".json", ".md", ".toml", ".yaml", ".yml", ".csv")):
            target = token
            target_kind = "path"
            break
    return " ".join(family_tokens), target, target_kind


def _failure_class(envelope: ObservationEnvelope) -> str | None:
    """Return a failure class string for a failed tool observation, or None."""

    if envelope.error is not None:
        return envelope.error.failure_class or envelope.error.reason_code or envelope.error.kind
    if envelope.exit_code is not None and envelope.exit_code != 0:
        return f"exit_{envelope.exit_code}"
    if not envelope.files_changed and envelope.exit_code == 0:
        return "no_effect"
    return None


def _active_blockers(ledger: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Return all active/candidate_resolved/exhausted blockers from the ledger."""

    blockers = ledger.get("blockers", []) if isinstance(ledger, Mapping) else []
    if not isinstance(blockers, list):
        return []
    return [
        dict(item)
        for item in blockers
        if isinstance(item, Mapping) and str(item.get("status", "")) in {"active", "candidate_resolved", "exhausted"}
    ]


def _build_suppressed_blocker_report(ledger: Mapping[str, Any]) -> DiscrepancyReport:
    """Build a DiscrepancyReport for a verifier call suppressed due to active blockers."""

    blocker_rows = _active_blockers(ledger)[:_REQUIREMENT_PREVIEW_LIMIT]
    requirements = tuple(
        RequirementResult(
            requirement=str(blocker.get("requirement", "")).strip() or "unresolved requirement",
            verdict="unverifiable",
            evidence=(
                str(blocker.get("insufficiency_reason", "")).strip()
                or "No new blocker-relevant evidence was provided."
            )
            + (
                ""
                if not list(blocker.get("required_next_evidence", []) or [])
                else f" Next evidence: {list(blocker.get('required_next_evidence', []) or [])[0]}"
            ),
            evidence_strength="weak",
            evidence_strength_reasons=("suppressed_verifier_without_new_relevant_evidence",),
            confidence="high",
            evidence_refs=tuple(str(item) for item in list(blocker.get("rejected_evidence_refs", []) or [])[:2]),
            unresolved=True,
        )
        for blocker in blocker_rows
    )
    summary = "Completion request rejected without a new verifier call because active blockers still require new relevant evidence."
    blocker_summaries = [
        f"{str(blocker.get('requirement', '')).strip()}: "
        f"{(list(blocker.get('required_next_evidence', []) or []) or ['new blocker-relevant evidence required'])[0]}"
        for blocker in blocker_rows
    ]
    if blocker_summaries:
        summary += " " + " | ".join(blocker_summaries)
    return DiscrepancyReport(
        requirements=requirements,
        reason_codes=("verifier_suppressed_no_new_relevant_evidence",),
        summary=summary,
        raw_response="suppressed_verifier_call",
    )


def _build_completion_evidence_gate_report(
    ledger: Mapping[str, Any],
    *,
    stated_requirements: list[str],
    finalize_reason: str | None,
    check_results: list[Any],
    action_digest: Mapping[str, Any],
) -> DiscrepancyReport | None:
    """Build a gate DiscrepancyReport when task_done has no evidence, or None."""

    from harness.aether2.control.requirements import _primary_requirement  # local import

    if finalize_reason != "task_done":
        return None
    if check_results or _has_independent_runtime_evidence(action_digest):
        return None

    requirement = _primary_requirement(ledger, stated_requirements)
    evidence = (
        "task_done did not provide any replayed checks and the harness "
        "did not observe independent runtime/service/session evidence. Provide "
        "a concrete externally observable check, or keep working."
    )
    result = RequirementResult(
        requirement=requirement or "completion claim",
        verdict="unverifiable",
        evidence=evidence,
        evidence_strength="weak",
        evidence_strength_reasons=("no_replayed_check", "no_independent_runtime_evidence"),
        evidence_provenance=("model_authored",),
        confidence="high",
        evidence_refs=("claim", "action_digest.service_monitoring"),
        unresolved=True,
    )
    return DiscrepancyReport(
        requirements=(result,),
        reason_codes=("completion_evidence_gate_rejected",),
        summary="Completion request rejected before verifier because no replayed check or independent runtime evidence was available.",
        raw_response="completion_evidence_gate",
    )


def _has_independent_runtime_evidence(action_digest: Mapping[str, Any]) -> bool:
    """Return True if action_digest carries independent runtime/service evidence."""

    service_monitoring = action_digest.get("service_monitoring")
    if not isinstance(service_monitoring, Mapping) or not service_monitoring.get("applies"):
        return False

    jobs = service_monitoring.get("jobs")
    if isinstance(jobs, Mapping):
        for payload in jobs.values():
            if not isinstance(payload, Mapping):
                continue
            after = payload.get("end")
            if isinstance(after, Mapping) and (after.get("alive") is True or after.get("exit_code") == 0):
                return True

    sessions = service_monitoring.get("sessions")
    if isinstance(sessions, Mapping):
        for payload in sessions.values():
            if isinstance(payload, Mapping) and payload.get("end_present") is True:
                return True

    services = service_monitoring.get("services")
    if isinstance(services, Mapping):
        for payload in services.values():
            if isinstance(payload, Mapping) and payload.get("end") is not None:
                return True

    return False
