export const state = {
  activeView: "overview",
  appMeta: null,
  config: {},
  daemonStatus: null,
  language: "en",
  theme: "red",
  engineAction: {
    action: null,
    busy: false,
    message: "",
    tone: "neutral",
    visible: false,
  },
  runtime: null,
  updater: null,
  skills: null,
  schedules: [],
  scheduleFile: "",
  scheduleError: "",
  runLogs: [],
  runLogFile: "",
  runLogError: "",
  daemonResources: [],
  daemonResourceCounts: {},
  daemonResourceError: "",
  daemonEvents: [],
  daemonEventFile: "",
  daemonEventError: "",
  settingsDirty: false,
};
